[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "https://snu-graduation-tracker.vercel.app"
additional_redirect_urls = ["http://localhost:5173", "http://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_required = true

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
redirect_uri = "http://localhost:54322/auth/v1/callback"

[db]
port = 54322
shadow_port = 54320
major_version = 15